name: PR Close Pipeline
on:
  pull_request:
    types: [closed]
env:
  nuget-username: chrisxpr
  src-dir: ./src/code
  cdk-dir: ./cdk/lib
  coverage-threshold: 0
  repo-organisation: architected
  team-pat: ${{ secrets.NUGET_PAT}}
  cdk_action: destroy
  aws_account_id: $ {{ secrets.AWS_ACCOUNT_ID_NONPROD }}
  aws_secret: ${{ secrets.AWS_SECRET}}
  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
  aws_region: ap-southeast-2
  service_key: frontend-management-api
  ecr_repository_name: frontend-management-api
  target_environment: x-${{ github.event.number}}

concurrency: alpha-${{ github.ref}}
jobs:
  dotnetBuild:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 20
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.aws_access_key_id }}
          aws-secret-access-key: ${{ env.aws_secret }}
          aws-region: ${{ env.aws_region }}

      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'

      - name: CDK Destroy
        run: cdk destroy
        working-directory: ${{ env.cdk-dir }}